version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - curl -sSL https://install.python-poetry.org | python3 -
      - ${HOME}/.local/bin/poetry export -f requirements.txt --dev -E docs --without-hashes > constraints.txt

python:
  install:
    - requirements: docs/requirements.txt
